# Configuration Parameters
parameters:
  # BLAST settings (User-configurable)
  blast:
    # Word size for BLAST alignment. Higher values speed up alignment but may reduce sensitivity.
    wordsize: 30
    # Minimum percentage identity for a BLAST match to be considered valid.
    perc_identity: 90
    # Number of threads to use for running BLAST
    num_threads: 2 
    # Maximum number of parallel BLAST jobs to run.
    max_parallel: 10 
  
  fusion_filter: 
    # Minimum anchor length for fusion pair
    AnchorLength: 15 
    # Length of the sequencing reads.
    ReadLength: 150 
    # Length of the Junction seqeunce
    JunctionSeq: 15 
  
  
# Fusion Filter Developer Settings (Advanced configuration for developers)
  fusion_filt_devmode:  
    subject_query: 20 
    gap_subject: 0   
    overlap_query: 10  
    gap: 5 
    JunctionDist: 100 
    ShanEnt_Seq: 50 
    BptDinucleotide: 2 
    TopHits: 3 
    Promiscioushits: 2 
    split: 1 
    span: 0 
    src_count_min: 2
    src_count_max: 100







 

     
