
# If need output with paralogous genes, type yes.
# Requiremnts: R packages are essential
# This step be skipped if you wish.  
with_paralogous_genes: yes

parameters:

  blast:
    wordsize: 30
    perc_identity: 90
    num_threads: 2 # number of threads to run the blast
    max_parallel: 10 # number jobs to run the blast  parallel
  
  fusion_filter:    
    AnchorLength: 15  # user  # read_length
    ReadLength: 150 #user 
    JunctionSeq: 15 #user 
  #  
  fusion_fil_devmode:  # developer mode 
    subject_query: 20 # dev
    gap_subject: 0   #dev 
    overlap_query: 10  #dev # Number of overlaps allowed between a single read mapping to two different transcripts 
    gap: 5 #dev
    JunctionDist: 100 #dev
    ShanEnt_Seq: 50 #dev
    BptDinucleotide: 2  #dev
    TopHits: 3 #dev
    Promiscioushits: 2 #dev
    split: 1 
    span: 0 
    src_count_min: 2
    src_count_max: 100








 

     
